version: "3"

services:
  app:
    build: .
    container_name: openai_fastapi_container
    environment:
      OPENAI_API_KEY: "17f82d1fc6fe4d0ba2a768d8836c3e89"
      OPENAI_ENDPOINT: "https://qag02.openai.azure.com/"
      MONGODB_HOST: "mongodb://mongodb_container:27020/"
      MONGODB_DATABASE: "conversationdb"
      MONGODB_COLLECTION: "learning_companion"
    volumes:
      - ./main.py:/app/main.py
    ports:
      - "80:8000"

  mongodb:
    image: mongo:4.4.9
    container_name: mongodb_container
    ports:
      - "127.0.0.1:27017:27017"

